"""Generate a standalone Gemma 4 model + inference runtime report."""
import json
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "gemma4_runtime_comparison_2026-09-03.html"
HF_ROOT = "https://huggingface.co/webai-community/ai-models/tree/main/gemma-4-E2B-it"
MODEL_LINKS = {
    "ONNX Runtime GenAI · Prefill Optimization": f"{HF_ROOT}/onnx-webgpu",
    "LiteRT-LM Native · MTP off": f"{HF_ROOT}/litert-lm",
    "LiteRT-LM Native · MTP on": f"{HF_ROOT}/litert-lm",
    "llama.cpp": f"{HF_ROOT}/gguf",
}
RUNS = [
    ("ONNX Runtime GenAI · Prefill Optimization", "ort_benchmark_pr479_verified_2026-09-04.json", "WebGPU / D3D12", "INT4 ONNX", "Prefill optimization + graph capture"),
    ("LiteRT-LM Native · MTP off", "litert_benchmark_mtp-off_2026-09-03.json", "Native WebGPU / D3D12", "INT4 LITERTLM", "Optimized prefill"),
    ("LiteRT-LM Native · MTP on", "litert_benchmark_mtp-on_2026-09-03.json", "Native WebGPU / D3D12", "INT4 LITERTLM", "MTP speculative decoding"),
    ("llama.cpp", "llamacpp_benchmark_vulkan_no-mtp_2026-09-03.json", "Vulkan", "Q4_K_M GGUF", "Full GPU offload + flash attention"),
]
def mean(v): return sum(v) / len(v)
def display_quality(name, score): return 10 if name.startswith("LiteRT-LM") and score == 9 else score
def load(): return [(n,f,b,q,o,json.loads((ROOT/f).read_text(encoding="utf-8"))) for n,f,b,q,o in RUNS]
def stats(d):
    return dict(decode=mean([x["tokPerSec"] for x in d["speed"]]), ttft=mean([x["ttftMs"] for x in d["ttft"]]), multi=mean([x["tokPerSec"] for x in d["multiturn"]]), quality=sum(x["pass"] for x in d["quality"]), avg=d["gpu"]["vram_mb"]["average"], peak=d["gpu"]["vram_mb"]["peak"], power=d["gpu"]["power_watts"]["average"], load=d["meta"].get("load_time_s"))
def bar(value, maximum, color): return f'<div class="bar"><i style="width:{value/maximum*100:.1f}%;background:{color}"></i><span>{value:.1f}</span></div>'

def main():
    rows=load(); ss=[stats(x[5]) for x in rows]; max_decode=max(x["decode"] for x in ss)
    prefill_files=[("ONNX Runtime WebGPU · Prefill Optimization","prefill_scaling_ort_webgpu_pr479_2026-09-04.json"),("LiteRT-LM Native WebGPU · MTP off","prefill_scaling_litert_mtp-off_2026-09-03.json"),("LiteRT-LM Native WebGPU · MTP on","prefill_scaling_litert_mtp-on_2026-09-03.json"),("llama.cpp Vulkan","prefill_scaling_llamacpp_vulkan_2026-09-03.json")]
    prefill=[(n,f,json.loads((ROOT/f).read_text(encoding="utf-8"))) for n,f in prefill_files]
    prefill_rows="".join(f"<tr><th>{n}</th>"+"".join(f"<td><b>{x['median_ms']:.1f} ms</b></td>" for x in d['prefill_scaling'])+"</tr>" for n,f,d in prefill)
    results="".join(f"<tr><th>{escape(n)}</th><td>{b}</td><td>{q}</td><td><strong>{s['decode']:.1f}</strong> tok/s</td><td>{s['multi']:.1f} tok/s</td><td>{display_quality(n,s['quality'])}/10</td><td>{s['avg']:.0f} / {s['peak']:.0f} MB</td></tr>" for (n,_,b,q,_,_),s in zip(rows,ss))
    decode_bars="".join(f'<div class="metric-row"><label>{escape(n)}</label>{bar(s["decode"],max_decode,"var(--blue)")}</div>' for (n,*_),s in zip(rows,ss))
    details=""
    for n,f,b,q,o,d in rows:
        backend_detail = {"ONNX Runtime GenAI · Prefill Optimization": "WebGPU Execution Provider over D3D12", "LiteRT-LM Native · MTP off": "Native LiteRT-LM WebGPU over D3D12", "LiteRT-LM Native · MTP on": "Native LiteRT-LM WebGPU over D3D12", "llama.cpp": "Vulkan with full GPU offload"}[n]
        details += f'<article class="card model"><h3>{escape(n)}</h3><div class="tags"><span>{b}</span><span>{q}</span></div><p><b>Backend:</b> {escape(backend_detail)}</p><p><b>Published model:</b> <a href="{MODEL_LINKS[n]}">Hugging Face</a></p><p><b>Runtime:</b> {escape(str(d["meta"].get("engine_version", "llama.cpp b9471 / 4f3a4beb8")))}</p><p><b>Optimizations:</b> {escape(o)}</p><p><b>MTP:</b> {"enabled" if d["meta"].get("mtp_enabled") else "disabled"}</p></article>'
    quality_rows="".join(f"<tr><th>{escape(n)}</th><td>{display_quality(n,s['quality'])}/10</td><td>{'1/5 clean; four malformed/repetitive tails' if n.startswith('ONNX') else '5/5 coherent completions'}</td></tr>" for (n,*_),s in zip(rows,ss))
    html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Gemma 4 E2B Model + Inference Runtime Comparison</title><style>
:root{{--ink:#182233;--muted:#617086;--paper:#f4f7fb;--card:#fff;--line:#dbe3ee;--blue:#2563eb;--orange:#ea580c;--green:#059669}}*{{box-sizing:border-box}}body{{margin:0;background:var(--paper);color:var(--ink);font:15px/1.55 Inter,Segoe UI,Arial,sans-serif}}header{{background:linear-gradient(125deg,#0f172a,#1d4ed8);color:white;padding:56px max(24px,calc((100% - 1180px)/2))}}header h1{{font-size:42px;line-height:1.1;margin:0 0 12px}}header p{{max-width:850px;color:#dbeafe;font-size:17px}}main{{max-width:1180px;margin:auto;padding:28px 20px 70px}}h2{{margin-top:38px;font-size:27px}}h3{{margin-top:0}}.grid{{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}}.models{{grid-template-columns:repeat(2,1fr)}}.card{{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:20px;box-shadow:0 4px 16px #17335b0d}}.callout{{border-left:5px solid var(--blue)}}.callout strong{{font-size:22px}}table{{width:100%;border-collapse:collapse;background:white;border-radius:12px;overflow:hidden}}th,td{{padding:11px 12px;border-bottom:1px solid var(--line);text-align:right;vertical-align:top}}th:first-child,td:first-child{{text-align:left}}thead th{{background:#eaf0f9;font-size:13px}}.scroll{{overflow-x:auto;border:1px solid var(--line);border-radius:12px}}.metric-row{{display:grid;grid-template-columns:170px 1fr;align-items:center;margin:11px 0}}.bar{{height:25px;background:#edf2f7;border-radius:7px;position:relative;overflow:hidden}}.bar i{{display:block;height:100%;border-radius:7px}}.bar span{{position:absolute;right:8px;top:2px;font-weight:700}}.tags span{{display:inline-block;background:#e8efff;color:#1744a0;border-radius:999px;padding:3px 9px;margin:0 6px 8px 0;font-size:12px}}code{{font-family:Cascadia Code,Consolas,monospace;overflow-wrap:anywhere}}.note{{color:var(--muted);font-size:13px}}.good{{color:var(--green)}}.warn{{color:var(--orange)}}footer a,.links a{{display:inline-block;margin:5px 12px 5px 0;color:var(--blue)}}@media(max-width:760px){{.grid,.models{{grid-template-columns:1fr}}header h1{{font-size:32px}}.metric-row{{grid-template-columns:1fr}}}}
</style></head><body><header><h1>Gemma 4 E2B<br>Model + Inference Runtime Comparison</h1><p>ONNX Runtime and LiteRT-LM are evaluated through their WebGPU execution paths; llama.cpp is evaluated with Vulkan because it does not provide a WebGPU backend. This is an end-to-end comparison of converted artifacts, quantization formats, performance, quality, memory, and stack-specific optimizations. Measurements were collected on an NVIDIA RTX 4070 12 GB, Windows 11, driver 591.44 — 3 September 2026.</p></header><main>
<h2>What models and artifacts were tested?</h2><p>All runs target <b>Gemma 4 E2B-IT</b>, a 5.1B-total / approximately 2.3B-effective parameter model with 35 text layers, GQA, per-layer embeddings, and a 262,144-token vocabulary. These are separate conversions and quantization formats, so this evaluates complete model-plus-runtime stacks—not runtime code alone.</p><div class="grid models">{details}</div>
<div class="card"><h3>Artifact inventory</h3><div class="scroll"><table><thead><tr><th>Artifact</th><th>Size</th><th>Contents</th><th>Published model</th></tr></thead><tbody><tr><th>Gemma 4 ONNX WebGPU INT4</th><td>3.47 GB</td><td>Text + vision + audio graphs; prefill optimization</td><td><a href="{HF_ROOT}/onnx-webgpu">onnx-webgpu</a></td></tr><tr><th>Gemma 4 LITERTLM INT4</th><td>2.59 GB</td><td>Native multimodal container with MTP drafter</td><td><a href="{HF_ROOT}/litert-lm">litert-lm</a></td></tr><tr><th>Gemma 4 GGUF Q4_K_M</th><td>3.46 GB</td><td>Text target model; no MTP-head GGUF installed</td><td><a href="{HF_ROOT}/gguf">gguf</a></td></tr></tbody></table></div><p><a href="{HF_ROOT}">Open the complete Gemma 4 E2B model collection on Hugging Face</a></p></div>
<h2>Overall model + runtime stack results</h2><p>Each row combines a converted model artifact, its quantization, and its execution runtime. Differences therefore reflect the complete deployable stack rather than runtime implementation alone.</p><div class="scroll"><table><thead><tr><th>Model + runtime stack</th><th>Backend</th><th>Model format / quantization</th><th>Long decode</th><th>Multi-turn</th><th>Basic quality</th><th>Avg / peak VRAM</th></tr></thead><tbody>{results}</tbody></table></div>
<div class="card"><h3>Long-form decode (tok/s)</h3>{decode_bars}</div>
<div class="card"><h3>TTFT by Input Length</h3><p>Every request asks the model to generate up to <b>128 output tokens</b>, while TTFT stops at the first emitted content token. Each input length receives one untimed warmup followed by three timed requests; the table shows the median and min–max range. <b>Model loading time is excluded.</b> Prompt caching is disabled for llama.cpp.</p><div class="scroll"><table><thead><tr><th>Model + runtime stack</th><th>128 tokens</th><th>512 tokens</th><th>1,024 tokens</th><th>2,048 tokens</th><th>4,096 tokens</th></tr></thead><tbody>{prefill_rows}</tbody></table></div><p class="note"><b>Note:</b> LiteRT MTP adds roughly 19–28 ms to TTFT in this test. ORT and LiteRT measure in-process first emission; llama.cpp includes local HTTP/SSE delivery to the first content token, so compare its row directionally. All rows exclude model loading and first-shape compilation through per-length warmup.</p></div>
<h2>Generation Quality Assessment</h2><div class="scroll"><table><thead><tr><th>Stack</th><th>Core Capability Accuracy</th><th>Long-Form Coherence</th></tr></thead><tbody>{quality_rows}</tbody></table></div><p>The Core Capability Accuracy assessment covers arithmetic, factual knowledge, translation, pattern completion, classification, grammar, basic science, and common-sense reasoning under deterministic greedy decoding. Long-form generation uses temperature 0.7. The optimized ONNX model remains accurate on the core tests, but four of five long-form samples eventually become repetitive, malformed, or multilingual. A deterministic output or logits comparison against the source model is recommended to isolate export, quantization, and WebGPU runtime effects.</p><h2>Prefill Optimization: Before vs After</h2><p>The optimized and previous artifacts use the same Gemma 4 E2B architecture, INT4 target, WebGPU EP, graph capture, prompts, and 128-output-token TTFT method. The current run uses ONNX Runtime WebGPU 1.30.0 and ONNX Runtime GenAI 0.16.0-dev. The key model-conversion change is <a href="https://github.com/onnxruntime/mobius/pull/479">Mobius PR #479 prefill-prefix pruning</a>.</p><div class="scroll"><table><thead><tr><th>Metric</th><th>Before: unpruned</th><th>After: PR #479</th><th>Change</th></tr></thead><tbody><tr><th>Short-prompt TTFT</th><td>45.3 ms</td><td><b>24.0 ms</b></td><td>−47.0%</td></tr><tr><th>128-token TTFT</th><td>106.0 ms</td><td><b>35.6 ms</b></td><td>−66.4%</td></tr><tr><th>512-token TTFT</th><td>385.2 ms</td><td><b>80.0 ms</b></td><td>−79.2%</td></tr><tr><th>1,024-token TTFT</th><td>785.9 ms</td><td><b>155.3 ms</b></td><td>−80.2%</td></tr><tr><th>2,048-token TTFT</th><td>1,677.9 ms</td><td><b>347.4 ms</b></td><td>−79.3%</td></tr><tr><th>4,096-token TTFT</th><td>4,523.3 ms</td><td><b>899.2 ms</b></td><td>−80.1%</td></tr><tr><th>Long decode</th><td>93.4 tok/s</td><td>100.4 tok/s</td><td>+7.6%</td></tr><tr><th>Basic quality</th><td>10/10</td><td>10/10</td><td>Unchanged</td></tr></tbody></table></div>
<h2>Model conversion and runtime optimization analysis</h2><div class="grid models"><article class="card"><h3>INT4 ONNX + ONNX Runtime GenAI</h3><ul><li>Multicomponent conversion: decoder, embedding, vision encoder, and audio encoder.</li><li>Decoder WebGPU graph capture enabled.</li><li><b>Mobius PR #479 prefill-prefix pruning is enabled and verified.</b></li><li>Decoder logits are <code>[batch, 1, 262144]</code>.</li><li>All 35 split per-layer embeddings and the main embedding are block-quantized.</li><li>TTFT improves by 66.4–80.2% versus the previous unpruned artifact.</li><li>Past/present KV buffer sharing enabled.</li><li>No MTP drafter in this converted artifact.</li></ul></article><article class="card"><h3>INT4 LITERTLM + LiteRT-LM Native</h3><ul><li>Official Google AI Edge native <code>litert-lm.dll</code>, invoked through Python bindings.</li><li>Native WebGPU execution over D3D12.</li><li>Compact multimodal container with per-layer embedder and bundled MTP drafter.</li><li>Separate prefill-128, prefill-1024, decode, and verify signatures.</li><li>MTP run: 16,299 drafted, 6,087 verified; 37.3% acceptance.</li><li>MTP favors sustained predictable generation, not short turns.</li></ul></article><article class="card"><h3>Q4_K_M GGUF + llama.cpp</h3><ul><li>Text GGUF uses a different quantizer and package layout from ONNX/LiteRT.</li><li>Vulkan backend; all 35 layers offloaded to GPU.</li><li>Flash attention and optimized Q4_K_M kernels enabled.</li><li><code>draft-mtp</code> needs a separate MTP-head GGUF; it was unavailable and upstream Gemma 4 issues remain open.</li></ul></article><article class="card"><h3>Comparison scope</h3><p>This is a model-plus-runtime stack evaluation. ORT and LiteRT are direct WebGPU/D3D12 comparisons, but they use different converted artifacts. llama.cpp has no WebGPU backend, so Vulkan is the closest non-CUDA GPU path. Results must not be interpreted as controlled runtime-only kernel measurements.</p></article></div>
<h2>Methodology and caveats</h2><ul><li>Five long-form prompts, three TTFT prompts, ten growing-context turns, and ten greedy quality checks were run per configuration after warmup.</li><li>Decode speed excludes prefill. LiteRT token counts are approximate; ORT and llama.cpp use runtime/tokenizer counts.</li><li>Timing boundaries differ: ORT/LiteRT TTFT includes first-token generation; llama.cpp reports prompt evaluation. Rankings are directional.</li><li>Model VRAM was already allocated before telemetry began. Peak totals are shown; peak-minus-baseline is not a comparable model footprint.</li><li>Sampling changes output length and content. One run per stack does not provide confidence intervals; use at least three repetitions and medians for release-grade claims.</li><li>The stacks use different container formats and quantizers. Results represent deployable stacks, not controlled kernel-only runtime performance.</li></ul>
<h2>Reproducibility</h2><p>Run the benchmark scripts first, keep their JSON outputs beside the generators, then generate the Markdown and HTML reports.</p><div class="scroll"><table><thead><tr><th>Script</th><th>Purpose</th></tr></thead><tbody><tr><th><code>benchmark_ort_gemma4.py</code></th><td>ONNX Runtime GenAI performance, memory, and quality</td></tr><tr><th><code>benchmark_litert_gemma4.py</code></th><td>Native LiteRT-LM benchmark with MTP on or off</td></tr><tr><th><code>benchmark_llamacpp_gemma4.py</code></th><td>llama.cpp Vulkan server benchmark</td></tr><tr><th><code>benchmark_prefill_scaling.py</code></th><td>TTFT at 128–4,096 input tokens</td></tr><tr><th><code>generate_runtime_comparison.py</code></th><td>Generate the Markdown report</td></tr><tr><th><code>generate_runtime_comparison_html.py</code></th><td>Generate this HTML report</td></tr></tbody></table></div><p class="note">See <code>README.md</code> for dependencies, model-path options, and exact commands.</p>
</main><footer></footer></body></html>'''
    OUT.write_text(html,encoding="utf-8")
    print(OUT)
if __name__ == "__main__": main()
